import proImg from '../assets/attractive-stylish-young-girl-business-clothes-posing-light-background-studio-concept-stylish-clothes-sophistication.jpg'

const Subproducts = [
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
    {
        name: 'Kalini',
        img: proImg,
        description: 'Kurta With Trousers & Duppata',
        price: 869,
        cuttedPrice: 4600,
        discount: 20,
        rating: 4.5,
        comment: '4.3k',
    },
];

export default Subproducts;
